apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tp7w
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-tp7w@sha256:fc68d52c7889d2498817325a25feebfcdff17789e4db93659bf79ecdb926309b
        name: my-nodejs
        resources: {}
status: {}
